# Generated by Django 4.1.4 on 2023-03-01 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoryname', models.CharField(max_length=100)),
                ('categorydescription', models.CharField(max_length=200)),
                ('categoryimage', models.ImageField(upload_to='sample')),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productname', models.CharField(max_length=100)),
                ('productprice', models.IntegerField()),
                ('productquantity', models.IntegerField()),
                ('productimage', models.ImageField(upload_to='sample')),
            ],
        ),
    ]
