# Generated by Django 4.1.4 on 2023-03-06 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=89)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=45)),
                ('lastname', models.CharField(max_length=56)),
                ('username', models.CharField(max_length=78)),
                ('password', models.CharField(max_length=80)),
                ('mobilenumber', models.IntegerField()),
                ('address', models.CharField(max_length=90)),
                ('city', models.CharField(max_length=80)),
                ('state', models.CharField(max_length=56)),
                ('zipcode', models.IntegerField()),
            ],
        ),
    ]
