# Generated by Django 4.1.4 on 2023-03-20 06:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0004_checkout'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkout',
            name='productquantity',
        ),
        migrations.AlterField(
            model_name='checkout',
            name='cartid',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='userapp.cartdb'),
        ),
    ]
