# Generated by Django 4.1.4 on 2023-03-21 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0006_remove_checkout_productname_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contactdb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=89)),
                ('email', models.CharField(max_length=80)),
                ('subject', models.CharField(max_length=78)),
                ('mssages', models.CharField(max_length=200)),
            ],
        ),
    ]
