# Generated by Django 4.1.4 on 2023-03-21 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0007_contactdb'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactdb',
            old_name='mssages',
            new_name='messages',
        ),
    ]
